/**
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pucrs.lp.scheme.SchemeRuntimeModule;
import pucrs.lp.scheme.SchemeStandaloneSetup;
import pucrs.lp.scheme.ide.SchemeIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SchemeIdeSetup extends SchemeStandaloneSetup {
  @Override
  public Injector createInjector() {
    SchemeRuntimeModule _schemeRuntimeModule = new SchemeRuntimeModule();
    SchemeIdeModule _schemeIdeModule = new SchemeIdeModule();
    return Guice.createInjector(Modules2.mixin(_schemeRuntimeModule, _schemeIdeModule));
  }
}
