/**
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme.ide;

import pucrs.lp.scheme.ide.AbstractSchemeIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SchemeIdeModule extends AbstractSchemeIdeModule {
}
