/*
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import pucrs.lp.scheme.ui.internal.SchemeActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SchemeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SchemeActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SchemeActivator activator = SchemeActivator.getInstance();
		return activator != null ? activator.getInjector(SchemeActivator.PUCRS_LP_SCHEME_SCHEME) : null;
	}

}
