/*
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SchemeRuntimeModule extends AbstractSchemeRuntimeModule {
}
