/*
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import pucrs.lp.scheme.scheme.Model

@ExtendWith(InjectionExtension)
@InjectWith(SchemeInjectorProvider)
class SchemeParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	
	
	@Test
	def void operacaoAritmeticaTest() {
		val result = parseHelper.parse('''
			(+ 2 3)
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void defineTest() {
		val result = parseHelper.parse('''
			(define x 10)
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void defineComParametroTest() {
		val result = parseHelper.parse('''
			(define (f x)
			  (+ x 1))
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void condicionalTest() {
		val result = parseHelper.parse('''
			(if (= 1 2) 
				1 
				0
			)
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void condicionalAninhadoTest() {
		val result = parseHelper.parse('''
			(if (= 1 2) 
				1 
				(if (= 3 3) 
					11 
					00
				)
			)
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
