/**
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme.validation;

import pucrs.lp.scheme.validation.AbstractSchemeValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SchemeValidator extends AbstractSchemeValidator {
}
