/**
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme;

import pucrs.lp.scheme.SchemeStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SchemeStandaloneSetup extends SchemeStandaloneSetupGenerated {
  public static void doSetup() {
    new SchemeStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
