/**
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme;

import pucrs.lp.scheme.AbstractSchemeRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SchemeRuntimeModule extends AbstractSchemeRuntimeModule {
}
