/**
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme.scoping;

import pucrs.lp.scheme.scoping.AbstractSchemeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SchemeScopeProvider extends AbstractSchemeScopeProvider {
}
