/**
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import pucrs.lp.scheme.ui.AbstractSchemeUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SchemeUiModule extends AbstractSchemeUiModule {
  public SchemeUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
