/*
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSchemeValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(pucrs.lp.scheme.scheme.SchemePackage.eINSTANCE);
		return result;
	}
}
