/**
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme.scheme;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see pucrs.lp.scheme.scheme.SchemePackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends EObject
{
} // Command
