/**
 * generated by Xtext 2.17.0
 */
package pucrs.lp.scheme.scheme;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conditional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pucrs.lp.scheme.scheme.Conditional#getAt <em>At</em>}</li>
 *   <li>{@link pucrs.lp.scheme.scheme.Conditional#getValue2 <em>Value2</em>}</li>
 *   <li>{@link pucrs.lp.scheme.scheme.Conditional#getCommands <em>Commands</em>}</li>
 * </ul>
 *
 * @see pucrs.lp.scheme.scheme.SchemePackage#getConditional()
 * @model
 * @generated
 */
public interface Conditional extends Command
{
  /**
   * Returns the value of the '<em><b>At</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>At</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>At</em>' attribute list.
   * @see pucrs.lp.scheme.scheme.SchemePackage#getConditional_At()
   * @model unique="false"
   * @generated
   */
  EList<String> getAt();

  /**
   * Returns the value of the '<em><b>Value2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value2</em>' attribute.
   * @see #setValue2(int)
   * @see pucrs.lp.scheme.scheme.SchemePackage#getConditional_Value2()
   * @model
   * @generated
   */
  int getValue2();

  /**
   * Sets the value of the '{@link pucrs.lp.scheme.scheme.Conditional#getValue2 <em>Value2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value2</em>' attribute.
   * @see #getValue2()
   * @generated
   */
  void setValue2(int value);

  /**
   * Returns the value of the '<em><b>Commands</b></em>' containment reference list.
   * The list contents are of type {@link pucrs.lp.scheme.scheme.Command}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Commands</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' containment reference list.
   * @see pucrs.lp.scheme.scheme.SchemePackage#getConditional_Commands()
   * @model containment="true"
   * @generated
   */
  EList<Command> getCommands();

} // Conditional
