/**
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme.ui.contentassist;

import pucrs.lp.scheme.ui.contentassist.AbstractSchemeProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SchemeProposalProvider extends AbstractSchemeProposalProvider {
}
