/*
 * generated by Xtext 2.17.0
 */
package pucrs.lp.scheme.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSchemeScopeProvider extends DelegatingScopeProvider {
}
