/**
 * generated by Xtext 2.17.0
 */
package pucrs.lp.scheme.scheme.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import pucrs.lp.scheme.scheme.Conditional;
import pucrs.lp.scheme.scheme.SchemePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Conditional</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link pucrs.lp.scheme.scheme.impl.ConditionalImpl#getAt <em>At</em>}</li>
 *   <li>{@link pucrs.lp.scheme.scheme.impl.ConditionalImpl#getValue2 <em>Value2</em>}</li>
 *   <li>{@link pucrs.lp.scheme.scheme.impl.ConditionalImpl#getValue3 <em>Value3</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConditionalImpl extends CommandImpl implements Conditional
{
  /**
   * The cached value of the '{@link #getAt() <em>At</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAt()
   * @generated
   * @ordered
   */
  protected EList<String> at;

  /**
   * The default value of the '{@link #getValue2() <em>Value2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue2()
   * @generated
   * @ordered
   */
  protected static final int VALUE2_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getValue2() <em>Value2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue2()
   * @generated
   * @ordered
   */
  protected int value2 = VALUE2_EDEFAULT;

  /**
   * The default value of the '{@link #getValue3() <em>Value3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue3()
   * @generated
   * @ordered
   */
  protected static final int VALUE3_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getValue3() <em>Value3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue3()
   * @generated
   * @ordered
   */
  protected int value3 = VALUE3_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConditionalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SchemePackage.Literals.CONDITIONAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getAt()
  {
    if (at == null)
    {
      at = new EDataTypeEList<String>(String.class, this, SchemePackage.CONDITIONAL__AT);
    }
    return at;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue2()
  {
    return value2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue2(int newValue2)
  {
    int oldValue2 = value2;
    value2 = newValue2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchemePackage.CONDITIONAL__VALUE2, oldValue2, value2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue3()
  {
    return value3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue3(int newValue3)
  {
    int oldValue3 = value3;
    value3 = newValue3;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchemePackage.CONDITIONAL__VALUE3, oldValue3, value3));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SchemePackage.CONDITIONAL__AT:
        return getAt();
      case SchemePackage.CONDITIONAL__VALUE2:
        return getValue2();
      case SchemePackage.CONDITIONAL__VALUE3:
        return getValue3();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SchemePackage.CONDITIONAL__AT:
        getAt().clear();
        getAt().addAll((Collection<? extends String>)newValue);
        return;
      case SchemePackage.CONDITIONAL__VALUE2:
        setValue2((Integer)newValue);
        return;
      case SchemePackage.CONDITIONAL__VALUE3:
        setValue3((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SchemePackage.CONDITIONAL__AT:
        getAt().clear();
        return;
      case SchemePackage.CONDITIONAL__VALUE2:
        setValue2(VALUE2_EDEFAULT);
        return;
      case SchemePackage.CONDITIONAL__VALUE3:
        setValue3(VALUE3_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SchemePackage.CONDITIONAL__AT:
        return at != null && !at.isEmpty();
      case SchemePackage.CONDITIONAL__VALUE2:
        return value2 != VALUE2_EDEFAULT;
      case SchemePackage.CONDITIONAL__VALUE3:
        return value3 != VALUE3_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (at: ");
    result.append(at);
    result.append(", value2: ");
    result.append(value2);
    result.append(", value3: ");
    result.append(value3);
    result.append(')');
    return result.toString();
  }

} //ConditionalImpl
