/*
 * generated by Xtext 2.17.0
 */
package pucrs.lp.scheme.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SchemeAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("pucrs/lp/scheme/parser/antlr/internal/InternalScheme.tokens");
	}
}
