/*
 * generated by Xtext 2.15.0
 */
package pucrs.lp.scheme.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import pucrs.lp.scheme.parser.antlr.internal.InternalSchemeParser;
import pucrs.lp.scheme.services.SchemeGrammarAccess;

public class SchemeParser extends AbstractAntlrParser {

	@Inject
	private SchemeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSchemeParser createParser(XtextTokenStream stream) {
		return new InternalSchemeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SchemeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SchemeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
